---
# Установка grafana

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install $(basename $1)
  debug:
    msg: "Role $(basename $1) is being applied to {{ inventory_hostname }}"
